services:
  myresume:
    image: nginx
    ports:
      - 8001:80
    volumes:
      # - ./:/usr/share/nginx/html
      - ./www:/var/www
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_ROOT=/var/www
