services:
  myresume:
    image: nginx
    ports:
      - 8001:80
    volumes:
      - ./www:/var/www/myresume
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_ROOT=/var/www/myresume
